# MP3 Tagger - Standard Konfiguration
# Kopiere diese Datei zu user_config.yaml und passe die Einstellungen an

# API-Konfiguration
api_keys:
  # MusicBrainz benötigt nur einen User-Agent String
  musicbrainz_user_agent: "mp3Tagger/1.0 (https://github.com/yourname/mp3Tagger)"
  
  # Last.fm API Key (kostenlos unter https://www.last.fm/api/account/create)
  lastfm_api_key: ""
  lastfm_shared_secret: ""
  
  # Spotify API (kostenlos unter https://developer.spotify.com/)
  spotify_client_id: ""
  spotify_client_secret: ""
  
  # YouTube Data API v3 (Google Cloud Console)
  youtube_api_key: ""
  
  # Discogs API (optional)
  discogs_user_token: ""

# Tag-Verwaltung
tag_settings:
  # Diese Tags werden niemals überschrieben
  protected_tags:
    - comment
    - user_defined_text_1
    - user_defined_text_2
    - custom_note
    - personal_rating
    
  # Auto-Update: Diese Tags werden automatisch ohne Nachfrage überschrieben
  auto_update_tags:
    - youtube_views
    - youtube_likes  
    - youtube_comments
    - youtube_dislikes
    - spotify_popularity
    - lastfm_playcount
    - lastfm_listeners
    - mp3_tagger_version
    - last_updated
    - metadata_source
    - external_ids
    
  # Interactive: Bei diesen Tags wird immer nachgefragt  
  interactive_tags:
    - artist
    - title
    - album
    - albumartist
    - date
    - year
    - genre
    
  # Diese Tags können verarbeitet werden
  processable_tags:
    - artist
    - albumartist
    - title
    - album
    - date
    - year
    - genre
    - track
    - tracktotal
    - disc
    - disctotal
    - youtube_url
    - youtube_views
    - youtube_likes
    - youtube_comments
    - youtube_dislikes
    - spotify_id
    - spotify_url
    - spotify_popularity
    - spotify_artist_followers
    - spotify_artist_monthly_listeners
    - spotify_preview_url
    - lastfm_url
    - lastfm_playcount
    - lastfm_listeners
    - popularity_score
    
  # Conflict Resolution Settings
  conflict_resolution:
    # Batch-Mode Einstellungen
    batch_processing:
      enabled: true
      # Nach X Konflikten automatisch Batch-Rules anbieten
      auto_batch_threshold: 5
      # Speichere Entscheidungen für ähnliche Konflikte
      remember_decisions: true
      # Maximale Anzahl interaktiver Nachfragen pro Session
      max_interactive_prompts: 20
      
    # Confidence-Schwellwerte für automatische Entscheidungen
    confidence_thresholds:      # Automatisch akzeptieren bei >= 95% Confidence
      auto_accept: 0.95
      # Empfehlung "Accept" bei >= 80% Confidence  
      recommend_accept: 0.80
      # Warnung bei < 60% Confidence
      warn_low_confidence: 0.60

# Benutzerdefinierte Tag-Mappings
custom_tags:
    # YouTube
    youtube_url: "WXXX:YOUTUBE_URL"
    youtube_views: "TXXX:YOUTUBE_VIEWS"
    youtube_likes: "TXXX:YOUTUBE_LIKES"
    youtube_comments: "TXXX:YOUTUBE_COMMENTS"
    youtube_dislikes: "TXXX:YOUTUBE_DISLIKES"
    youtube_channel: "TXXX:YOUTUBE_CHANNEL"
      # Spotify
    spotify_id: "TXXX:SPOTIFY_ID"
    spotify_url: "WXXX:SPOTIFY_URL"
    spotify_popularity: "TXXX:SPOTIFY_POPULARITY"
    spotify_artist_followers: "TXXX:SPOTIFY_ARTIST_FOLLOWERS"
    spotify_artist_monthly_listeners: "TXXX:SPOTIFY_MONTHLY_LISTENERS"
    spotify_preview_url: "WXXX:SPOTIFY_PREVIEW_URL"
    
    # Last.fm
    lastfm_url: "WXXX:LASTFM_URL"  
    lastfm_playcount: "TXXX:LASTFM_PLAYCOUNT"
    lastfm_listeners: "TXXX:LASTFM_LISTENERS"
    
    # Allgemeine Metadaten
    popularity_score: "TXXX:POPULARITY_SCORE"
    
    # Weitere Plattformen (vorbereitet)
    # soundcloud_url: "WXXX:SOUNDCLOUD_URL"
    # bandcamp_url: "WXXX:BANDCAMP_URL"
    # apple_music_url: "WXXX:APPLE_MUSIC_URL"

# Matching-Einstellungen
matching_settings:
  # Minimum Confidence Score (0-100)
  min_confidence: 80
  
  # Fuzzy-Matching Threshold (0.0-1.0)
  fuzzy_threshold: 0.8
  
  # Maximale Ergebnisse pro API-Anfrage
  max_results_per_query: 10
  
  # Timeout für API-Anfragen (Sekunden)
  api_timeout: 30
  
  # Retry-Versuche bei fehlgeschlagenen API-Anfragen
  max_retries: 3

# YouTube-spezifische Einstellungen
youtube_settings:
  # Suchformat für YouTube-Videos
  search_formats:
    - "{artist} - {title} official"
    - "{artist} {title} official music video"
    - "{artist} {title}"
    - "{title} {artist}"
  
  # Minimum View Count für Video-Auswahl
  min_view_count: 1000
  
  # Bevorzuge offizielle Kanäle
  prefer_official_channels: true
  
  # Blacklist für Kanäle/Uploader
  channel_blacklist:
    - "lyrics"
    - "karaoke"
    - "instrumental"
    - "cover"

# Genre-Einstellungen
genre_settings:
  # Maximale Anzahl Genres pro Song
  max_genres: 3
  
  # Genre-Priorität (höhere Werte = höhere Priorität)
  genre_priority:
    Rock: 10
    Pop: 9
    Hip-Hop: 8
    Electronic: 7
    Jazz: 6
    Classical: 5
  
  # Genre-Mappings zwischen verschiedenen APIs
  genre_mappings:
    "Hip Hop": "Hip-Hop"
    "R&B": "R&B/Soul"
    "Dance": "Electronic"
    "Techno": "Electronic"

# Logging-Einstellungen
logging:
  # Log-Level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: "INFO"
  
  # Log-Datei-Pfad (relativ zum Projekt-Root)
  file: "logs/mp3_tagger.log"
  
  # Maximale Log-Datei-Größe (MB)
  max_file_size: 10
  
  # Anzahl Log-Dateien als Backup
  backup_count: 5
  
  # Konsolen-Output aktivieren
  console_output: true

# Performance-Einstellungen
performance:
  # Anzahl paralleler API-Anfragen
  max_concurrent_requests: 5
  
  # Cache-Einstellungen
  enable_cache: true
  cache_duration_days: 30
  cache_directory: "cache"
  
  # Batch-Größe für Datei-Verarbeitung
  batch_size: 50

# Backup-Einstellungen
# WICHTIGER HINWEIS zur In-Memory-Backup-Strategie:
# ===================================================
# Die In-Memory-Strategie verarbeitet immer nur EINE Datei zur Zeit:
# 1. Datei in RAM laden
# 2. Tags ändern 
# 3. Bei Erfolg: Datei schreiben, RAM freigeben
# 4. Bei Fehler: Aus RAM wiederherstellen
# 
# Daher ist diese Strategie für JEDE Bibliotheksgröße geeignet,
# da nie mehr als eine MP3-Datei gleichzeitig im Speicher gehalten wird.
# Das "max_memory_mb" Limit ist somit obsolet für diese Strategie.

backup:
  # Automatische Backups vor Tag-Änderungen
  auto_backup: true
    # Backup-Strategie (changelog, in_memory, selective, full_copy, disabled)
  # changelog: Leichtgewichtige JSON-basierte Änderungsprotokolle (empfohlen)
  # in_memory: RAM-basierte Transaktions-Backups - Eine Datei pro Zeit im RAM
  # selective: Nur kritische Tags als kompakte JSON-Backups
  # full_copy: Vollständige Dateikopien (nur für kleine Bibliotheken)
  # disabled: Keine Backups
  strategy: "changelog"
  
  # Backup-Verzeichnis
  directory: "backups"
  
  # Maximales Alter der Backups (Tage)
  max_age_days: 30
  
  # Kritische Tags für Selective Backup-Strategie
  critical_tags:
    - "TIT2"      # Title
    - "TPE1"      # Artist  
    - "TALB"      # Album
    - "TDRC"      # Date
    - "TCON"      # Genre
    - "TPE2"      # Album Artist
    - "TRCK"      # Track Number
    - "artist"    # Mutagen Key
    - "title"     # Mutagen Key
    - "album"     # Mutagen Key
    - "date"      # Mutagen Key
    - "genre"     # Mutagen Key
    # Komprimierung der Backups (nur für full_copy)
  compress: false
